global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'chaos-orchestrator'
    static_configs:
      - targets: ['chaos-orchestrator:5000']
    metrics_path: '/metrics'
    scrape_interval: 5s